# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - FIRSTChesapeakeDiscordBot

on:
  push:
    branches:
      - v2
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv --copies antenv
          source antenv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U "discord.py[voice]"
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install ffmpeg -y

#      - name: Upload artifact for deployment jobs
#        uses: actions/upload-artifact@v2
#        with:
#          name: python-app
#          path: .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'FIRSTChesapeakeDiscordBot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F8BB4884D40541BEA0DE11753A13CA6F }}
          startup-command: python src/bot.py
